### ISSUE TITLE
Build with version information

### ISSUE THREAD

**Issue by francislavoie** [ArisuOngaku/aur-caddy#3]
Please use the instructions in https://github.com/caddyserver/caddy#with-version-information-andor-plugins (or use `xcaddy`) to build the releases.

We've had a few users come to the https://caddy.community forums and they gave `(devel)` as their output of `caddy version` which isn't helpful in helping them debug the issues they're facing.

Also as an aside, it would be great if you could transition to `/etc/caddy/Caddyfile` instead of `caddy.conf` in the service files. `caddy.conf` is not a Caddy standard and it simply complicates things. Filenames that begin with `Caddyfile` are automatically detected as using the Caddyfile adapter, so it avoids needing the `--adapter` argument.

**Comment by ashpieboop** [comment]
Thanks for your issue! I came up with a working draft where `caddy version` gives me:

```
v2.1.1 h1:X9k1+ehZPYYrSqBvf/ocUgdLSRIuiNiMo7CvyGUQKeA=
```

~~Is this correct?~~ I checked it against the official binary; it checks up. I'll close this issue once the I publish the new version of PKGBUILD.
